import os
import IECore
import Gaffer
import GafferUI
import functools

# ---------------------------------------------------------------------
# ENV → DICT
# ---------------------------------------------------------------------

def get_context_env():
    return dict(
        origin_projects_root=os.getenv("ORIGIN_PROJECTS_ROOT"),
        session_filename=os.getenv("SESSION_FILENAME"),
        session_id=os.getenv("SESSION_ID"),
        show_name=os.getenv("SHOW_NAME"),
        project_publishes=os.getenv("PROJECT_PUBLISHES"),
        project_work=os.getenv("PROJECT_WORK"),
        project_control=os.getenv("PROJECT_CONTROL"),
        origin_path_hierarchy=os.getenv("ORIGIN_PATH_HIERARCHY"),
        entity_name=os.getenv("ENTITY_NAME"),
        entity_type=os.getenv("ENTITY_TYPE"),
        entity_id=os.getenv("ENTITY_ID"),
        task_name=os.getenv("TASK_NAME"),
        task_type=os.getenv("TASK_TYPE"),
        task_id=os.getenv("TASK_ID"),
        db_asset_stream_id=os.getenv("DB_ASSET_STREAM_ID"),
        db_asset_type=os.getenv("DB_ASSET_TYPE"),
        db_asset_id=os.getenv("DB_ASSET_ID"),
        db_asset_version_id=os.getenv("DB_ASSET_VERSION_ID"),
        asset_breakdown_id=os.getenv("ASSET_BREAKDOWN_ID"),
    )

# ---------------------------------------------------------------------
# CONTEXT REBUILD
# ---------------------------------------------------------------------

def rebuildGlobalContext(script):

    ctx = script.context()

    for k, v in get_context_env().items():
        if v is not None:
            ctx[k] = str(v)

# ---------------------------------------------------------------------
# OPTIONAL UI MIRROR
# ---------------------------------------------------------------------

def mirrorToScriptVariables(script):

    variables = script["variables"]

    for k, v in get_context_env().items():
        value = str(v or "")

        if k not in variables:
            variables.addMember(k, IECore.StringData(value), k)
        else:
            variables[k]["value"].setValue(value)

        Gaffer.MetadataAlgo.setReadOnly(variables[k]["name"], True)


def _remove_origin_context(script):
    protected_variables = ['imageCataloguePort', 'projectName', 'projectRootDirectory', 'renderPass']

    root_vars = script["variables"]
    for var in root_vars.children():
        var_name = var.getName()
        if var_name not in protected_variables:
            root_vars.removeChild(var)

def _create_origin_context(script):
    root_vars = script["variables"]

    get_orig_ctx = get_context_env()

    for ctx_name, cx_val in get_orig_ctx.items():
        root_vars.addChild(Gaffer.NameValuePlug(ctx_name, Gaffer.StringPlug("value", defaultValue=str(cx_val))))


def refresh_origin_context(script):
    _remove_origin_context(script)
    _create_origin_context(script)
    return script

# ---------------------------------------------------------------------
# ORIGIN → OPEN (MENU COMMAND)
# ---------------------------------------------------------------------

def __pathAndBookmarks( scriptWindow ) :

    bookmarks = GafferUI.Bookmarks.acquire(
        scriptWindow,
        pathType = Gaffer.FileSystemPath,
        category = "script",
    )

    currentFileName = scriptWindow.scriptNode()["fileName"].getValue()
    if currentFileName :
        path = Gaffer.FileSystemPath( os.path.dirname( os.path.abspath( currentFileName ) ) )
    else :
        path = Gaffer.FileSystemPath( bookmarks.getDefault( scriptWindow ) )

    path.setFilter( Gaffer.FileSystemPath.createStandardFilter( [ "gfr" ] ) )

    return path, bookmarks


def addRecentFile( application, fileName, *_reserved ) :

    if isinstance( application, Gaffer.Application ) :
        applicationRoot = application.root()
    else :
        applicationRoot = application

    try :
        applicationRoot.__recentFiles
    except AttributeError :
        applicationRoot.__recentFiles = []

    if fileName in applicationRoot.__recentFiles :
        applicationRoot.__recentFiles.remove( fileName )

    applicationRoot.__recentFiles.insert( 0, fileName )
    del applicationRoot.__recentFiles[25:]

    # Accessing via builtins to avoid shadowing by our own `open()` method above.
    with __builtins__["open"]( applicationRoot.preferencesLocation() / "recentFiles.py", "w" ) as f :

        f.write( "# This file was automatically generated by Gaffer.\n" )
        f.write( "# Do not edit this file - it will be overwritten.\n\n" )

        f.write( "import GafferUI\n" )
        for fileName in reversed( applicationRoot.__recentFiles ) :
            f.write( "GafferUI.FileMenu.addRecentFile( application, {} )\n".format( repr( fileName ) ) )

## A function suitable as the command for a File/Save menu item. It must be invoked from a menu which
# has a ScriptWindow in its ancestry.

def __addScript( application, fileName, dialogueParentWindow = None, asNew = False ) :

    recoveryFileName = None
    backups = GafferUI.Backups.acquire( application, createIfNecessary = False )
    if backups is not None :
        recoveryFileName = backups.recoveryFile( fileName )
        if recoveryFileName :
            dialogue = GafferUI.ConfirmationDialogue(
                title = "Backup Available",
                message = "A more recent backup is available. Open backup instead?",
                confirmLabel = "Open Backup",
                cancelLabel = "Open",
            )
            useBackup = dialogue.waitForConfirmation( parentWindow = dialogueParentWindow )
            if useBackup is None :
                return
            elif not useBackup :
                recoveryFileName = None
            dialogue.setVisible( False )

    script = Gaffer.ScriptNode()
    script["fileName"].setValue( recoveryFileName or fileName )

    dialogue = GafferUI.BackgroundTaskDialogue( "Loading" )
    result = dialogue.waitForBackgroundTask( functools.partial( script.load, continueOnError = True, ), dialogueParentWindow )
    if isinstance( result, IECore.Cancelled ) :
        return

    if asNew or recoveryFileName :
        # If we loaded a backup (or as new), rename the script to the old
        # filename (or nothing) so the user can resave and continue as before.
        script["fileName"].setValue( "" if asNew else fileName )
        script["unsavedChanges"].setValue( True )

    application["scripts"].addChild( script )

    if not asNew:
        GafferUI.FileMenu.addRecentFile( application, fileName )

    return script


def __open( currentScript, fileName ) :

    application = currentScript.ancestor( Gaffer.ApplicationRoot )
    currentWindow = GafferUI.ScriptWindow.acquire( currentScript )

    script = __addScript( application, fileName, dialogueParentWindow = currentWindow )
    if not script :
        return

    refreshed_script = refresh_origin_context(script)

    if not currentScript["fileName"].getValue() and not currentScript["unsavedChanges"].getValue() :
        # the current script is empty - the user will think of the operation as loading
        # the new script into the current window, rather than adding a new window. so make it
        # look like that.
        newWindow = GafferUI.ScriptWindow.acquire( refreshed_script )

        ## \todo We probably want a way of querying and setting geometry in the public API
        newWindow._qtWidget().restoreGeometry( currentWindow._qtWidget().saveGeometry() )
        currentWindow.setVisible( False )
        application["scripts"].removeChild( currentScript )
        # Defer destruction of `currentWindow` to avoid Qt crash (because we are invoked from
        # a menu parented to it).
        GafferUI.WidgetAlgo.keepUntilIdle( currentWindow )


def __originOpen( menu ) :

    scriptWindow = menu.ancestor( GafferUI.ScriptWindow )
    path, bookmarks = __pathAndBookmarks( scriptWindow )
    currentScript = scriptWindow.scriptNode()

    dialogue = GafferUI.PathChooserDialogue(path,
                                            title="Open Script...",
                                            confirmLabel="Open",
                                            valid=True,
                                            leaf=True,
                                            bookmarks=bookmarks)


    path = dialogue.waitForPath( parentWindow = scriptWindow )

    if not path :
        return

    __open( currentScript, str( path ) )


GafferUI.ScriptWindow.menuDefinition(application).append("/ORIGIN/Open (Rebuild Context)", {"command": __originOpen})

